// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GameHalfDisplay: typeof import('./src/components/league-admin/game-half-display.vue')['default']
    GameHalfForm: typeof import('./src/components/league-admin/game-half-form.vue')['default']
    Games: typeof import('./src/components/league-admin/games.vue')['default']
    LeagueDashboard: typeof import('./src/components/dashboard/league-dashboard.vue')['default']
    LeaguePlayers: typeof import('./src/components/league-admin/league-players.vue')['default']
    PlayerFormModal: typeof import('./src/components/league-admin/player-form-modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
